In [ ]:
#1. Import the NUMPY package under the name np.

In [2]:
import numpy as np


In [3]:
#Print the NUMPY version and the configuration.
print(np.__version__)
print(np.show_config())

1.24.3
blas_armpl_info:
  NOT AVAILABLE
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ironhack/anaconda\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/ironhack/anaconda\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ironhack/anaconda\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/ironhack/anaconda\\Library\\include']
lapack_armpl_info:
  NOT AVAILABLE
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ironhack/anaconda\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/ironhack/anaconda\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ironhack/anaconda\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/ironhack/anaconda\\Library\\include']
Supported

In [4]:
#3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
# Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?
import random as rm

a = np.random.random((2,3,5))

a


array([[[0.74306883, 0.36101204, 0.12510191, 0.36811212, 0.3465378 ],
        [0.37264691, 0.25459206, 0.98969051, 0.306466  , 0.41282019],
        [0.46705035, 0.73767709, 0.58436705, 0.27073718, 0.25654506]],

       [[0.97164716, 0.94899617, 0.0887096 , 0.27771341, 0.16720887],
        [0.13734392, 0.61875165, 0.56186384, 0.51156407, 0.8831647 ],
        [0.01903005, 0.61739721, 0.88735203, 0.5840752 , 0.95856778]]])

In [5]:
a_1=np.random.random((3,5))
a_2=np.random.random((3,5))
print(a_1)
print('')
print(a_2)
a_mix_a1_a2= np.concatenate((a_1,a_2),axis=0)
a_mix_a1_a2
#fallido

[[0.89772307 0.72687325 0.85859864 0.66389284 0.98593252]
 [0.36025314 0.18473864 0.9380508  0.00822788 0.00775675]
 [0.98608809 0.4263458  0.96097914 0.30219403 0.22177454]]

[[0.77617794 0.7349002  0.3129752  0.36919888 0.41763785]
 [0.89153481 0.71851958 0.48887681 0.32103725 0.61468069]
 [0.74316531 0.65329704 0.77546282 0.97741754 0.15406743]]


array([[0.89772307, 0.72687325, 0.85859864, 0.66389284, 0.98593252],
       [0.36025314, 0.18473864, 0.9380508 , 0.00822788, 0.00775675],
       [0.98608809, 0.4263458 , 0.96097914, 0.30219403, 0.22177454],
       [0.77617794, 0.7349002 , 0.3129752 , 0.36919888, 0.41763785],
       [0.89153481, 0.71851958, 0.48887681, 0.32103725, 0.61468069],
       [0.74316531, 0.65329704, 0.77546282, 0.97741754, 0.15406743]])

In [6]:
a_3= np.stack((a_1,a_2))
a_3

array([[[0.89772307, 0.72687325, 0.85859864, 0.66389284, 0.98593252],
        [0.36025314, 0.18473864, 0.9380508 , 0.00822788, 0.00775675],
        [0.98608809, 0.4263458 , 0.96097914, 0.30219403, 0.22177454]],

       [[0.77617794, 0.7349002 , 0.3129752 , 0.36919888, 0.41763785],
        [0.89153481, 0.71851958, 0.48887681, 0.32103725, 0.61468069],
        [0.74316531, 0.65329704, 0.77546282, 0.97741754, 0.15406743]]])

In [7]:
#4. Print a.
print(a)

[[[0.74306883 0.36101204 0.12510191 0.36811212 0.3465378 ]
  [0.37264691 0.25459206 0.98969051 0.306466   0.41282019]
  [0.46705035 0.73767709 0.58436705 0.27073718 0.25654506]]

 [[0.97164716 0.94899617 0.0887096  0.27771341 0.16720887]
  [0.13734392 0.61875165 0.56186384 0.51156407 0.8831647 ]
  [0.01903005 0.61739721 0.88735203 0.5840752  0.95856778]]]


In [8]:
#5. Create a 5x2x3 3-dimensional array with all values equaling 1.
#Assign the array to variable "b"
b = np.ones((5,2,3))
b

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [9]:
#6. Print b
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


In [10]:
#7. Do a and b have the same size? How do you prove that in Python code?
print(b.size)
print(a.size)

30
30


In [11]:
#8. Are you able to add a and b? Why or why not?
#no because they dont have the same shape
print(b.shape)
print(a.shape)

(5, 2, 3)
(2, 3, 5)


In [12]:
#9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".

In [13]:
c=b.reshape(2,3,5)
c.shape


(2, 3, 5)

In [14]:
#10. Try to add a and c. Now it should work. Assign the sum to varialbe "d". But why does it work now?
d= a + c
#because now both arrays have the same shape

In [15]:
#11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.
print(a)
print('')
print(d)
# the value is the same you just sum c which is a array of ones


[[[0.74306883 0.36101204 0.12510191 0.36811212 0.3465378 ]
  [0.37264691 0.25459206 0.98969051 0.306466   0.41282019]
  [0.46705035 0.73767709 0.58436705 0.27073718 0.25654506]]

 [[0.97164716 0.94899617 0.0887096  0.27771341 0.16720887]
  [0.13734392 0.61875165 0.56186384 0.51156407 0.8831647 ]
  [0.01903005 0.61739721 0.88735203 0.5840752  0.95856778]]]

[[[1.74306883 1.36101204 1.12510191 1.36811212 1.3465378 ]
  [1.37264691 1.25459206 1.98969051 1.306466   1.41282019]
  [1.46705035 1.73767709 1.58436705 1.27073718 1.25654506]]

 [[1.97164716 1.94899617 1.0887096  1.27771341 1.16720887]
  [1.13734392 1.61875165 1.56186384 1.51156407 1.8831647 ]
  [1.01903005 1.61739721 1.88735203 1.5840752  1.95856778]]]


In [16]:
#12. Multiply a and c. Assign the result to e.
e= np.multiply(a,c)
e

array([[[0.74306883, 0.36101204, 0.12510191, 0.36811212, 0.3465378 ],
        [0.37264691, 0.25459206, 0.98969051, 0.306466  , 0.41282019],
        [0.46705035, 0.73767709, 0.58436705, 0.27073718, 0.25654506]],

       [[0.97164716, 0.94899617, 0.0887096 , 0.27771341, 0.16720887],
        [0.13734392, 0.61875165, 0.56186384, 0.51156407, 0.8831647 ],
        [0.01903005, 0.61739721, 0.88735203, 0.5840752 , 0.95856778]]])

In [17]:
#13. Does e equal to a? Why or why not?
a ==e
# yes because c is an array of only 1, so is going to have the same values inside 

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

In [18]:
#14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"
d_max= d.max()
d_min = d.min()
d_mean = d.mean()
print(d_max)
print(d_min)
print(d_mean)

1.9896905059562817
1.0190300472017149
1.4943270247081686


In [19]:
#15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.
shape=(2,3,5)
f = np.empty(shape)
print(f)

[[[0.74306883 0.36101204 0.12510191 0.36811212 0.3465378 ]
  [0.37264691 0.25459206 0.98969051 0.306466   0.41282019]
  [0.46705035 0.73767709 0.58436705 0.27073718 0.25654506]]

 [[0.97164716 0.94899617 0.0887096  0.27771341 0.16720887]
  [0.13734392 0.61875165 0.56186384 0.51156407 0.8831647 ]
  [0.01903005 0.61739721 0.88735203 0.5840752  0.95856778]]]


#16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.
d_max
d_min 
d_mean 

In [23]:
f = np.zeros_like(d)
for i in range(d.shape[0]):
    for j in range(d.shape[1]):
        for k in range(d.shape[2]):
            if d_min < d[i, j, k] < d_mean:
                f[i, j, k] = 25
            elif d_mean < d[i, j, k] < d_max:
                f[i, j, k] = 75
            elif d[i, j, k] == d_mean:
                f[i, j, k] = 50
            elif d[i, j, k] == d_min:
                f[i, j, k] = 0
            elif d[i, j, k] == d_max:
                f[i, j, k] = 100

# 17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])

In [24]:
print(f)
print(d)

[[[ 75.  25.  25.  25.  25.]
  [ 25.  25. 100.  25.  25.]
  [ 25.  75.  75.  25.  25.]]

 [[ 75.  75.  25.  25.  25.]
  [ 25.  75.  75.  75.  75.]
  [  0.  75.  75.  75.  75.]]]
[[[1.74306883 1.36101204 1.12510191 1.36811212 1.3465378 ]
  [1.37264691 1.25459206 1.98969051 1.306466   1.41282019]
  [1.46705035 1.73767709 1.58436705 1.27073718 1.25654506]]

 [[1.97164716 1.94899617 1.0887096  1.27771341 1.16720887]
  [1.13734392 1.61875165 1.56186384 1.51156407 1.8831647 ]
  [1.01903005 1.61739721 1.88735203 1.5840752  1.95856778]]]
