#1. Import the NUMPY package under the name np.

In [105]:
import numpy as np

#2. Print the NUMPY version and the configuration.

In [106]:
print("NumPy Version:", np.__version__)

NumPy Version: 1.26.0


#3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a" 

#Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [107]:
a = np.random.random((2, 3, 5))

a

array([[[5.79618918e-01, 7.24202712e-01, 2.13365839e-01, 2.59379005e-01,
         1.54503620e-01],
        [4.46199668e-01, 7.37717823e-01, 2.18994112e-01, 7.56013044e-01,
         6.31952849e-01],
        [7.24095656e-01, 2.22476762e-01, 4.42510400e-01, 8.76364667e-01,
         1.90013987e-01]],

       [[9.67161757e-01, 9.49326898e-01, 9.64298388e-01, 4.89230913e-01,
         9.25563395e-01],
        [5.82107908e-01, 9.02968948e-01, 6.85205450e-01, 5.84698912e-01,
         3.23637821e-01],
        [7.05360571e-01, 2.08732526e-04, 4.80901925e-01, 3.46303112e-01,
         5.67545115e-01]]])

In [108]:

shape = (2, 3, 5)

a = np.empty(shape)

for i in range(shape[0]):
    for j in range(shape[1]):
        for k in range(shape[2]):
            a[i, j, k] = np.random.rand()

a
    

array([[[0.26727447, 0.38505958, 0.69800222, 0.49638528, 0.1392777 ],
        [0.97841362, 0.36944353, 0.26915608, 0.0255116 , 0.02835993],
        [0.69948507, 0.58401733, 0.16990603, 0.75645409, 0.38969399]],

       [[0.14602543, 0.09875691, 0.27001988, 0.95211146, 0.95838537],
        [0.36198715, 0.2659687 , 0.88452459, 0.13955331, 0.27718488],
        [0.09700158, 0.10031466, 0.93383485, 0.8424265 , 0.20742193]]])

#4. Print a.

In [109]:
print (a)

[[[0.26727447 0.38505958 0.69800222 0.49638528 0.1392777 ]
  [0.97841362 0.36944353 0.26915608 0.0255116  0.02835993]
  [0.69948507 0.58401733 0.16990603 0.75645409 0.38969399]]

 [[0.14602543 0.09875691 0.27001988 0.95211146 0.95838537]
  [0.36198715 0.2659687  0.88452459 0.13955331 0.27718488]
  [0.09700158 0.10031466 0.93383485 0.8424265  0.20742193]]]


#5. Create a 5x2x3 3-dimensional array with all values equaling 1.
#Assign the array to variable "b"

In [110]:
b = np.ones((5, 2, 3))

b

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

#6. Print b.

In [111]:
print (b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


#7. Do a and b have the same size? How do you prove that in Python code?

In [112]:

a = np.random.random((2, 3, 5))

b = np.ones((5, 2, 3))

if a.size == b.size:
    print("Arrays 'a' and 'b' have the same size.")
else:
    print("Arrays 'a' and 'b' do not have the same size.")

Arrays 'a' and 'b' have the same size.


In [113]:

a = np.random.random((2, 3, 5))

b = np.ones((5, 2, 3))

if a.shape == b.shape:
    print("Arrays 'a' and 'b' have the same size.")
else:
    print("Arrays 'a' and 'b' do not have the same size.")

Arrays 'a' and 'b' do not have the same size.


#8. Are you able to add a and b? Why or why not?

#9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".

In [114]:
c = np.transpose(b,(1,2,0))
print(c)

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


#10. Try to add a and c. Now it should work. Assign the sum to varialbe "d". But why does it work now?

In [115]:
d = a + c

d

array([[[1.11020846, 1.47331585, 1.76997304, 1.03925686, 1.2131871 ],
        [1.03224292, 1.11676302, 1.10623307, 1.98137287, 1.67601116],
        [1.01701779, 1.73777258, 1.90392873, 1.80898349, 1.11141536]],

       [[1.59211324, 1.97018936, 1.12910177, 1.29515052, 1.71266714],
        [1.75119378, 1.80203319, 1.58854164, 1.70369114, 1.61085821],
        [1.92919861, 1.01558343, 1.11564075, 1.33505908, 1.70180552]]])

#11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.

In [116]:
print(a)

print(d)

[[[0.11020846 0.47331585 0.76997304 0.03925686 0.2131871 ]
  [0.03224292 0.11676302 0.10623307 0.98137287 0.67601116]
  [0.01701779 0.73777258 0.90392873 0.80898349 0.11141536]]

 [[0.59211324 0.97018936 0.12910177 0.29515052 0.71266714]
  [0.75119378 0.80203319 0.58854164 0.70369114 0.61085821]
  [0.92919861 0.01558343 0.11564075 0.33505908 0.70180552]]]
[[[1.11020846 1.47331585 1.76997304 1.03925686 1.2131871 ]
  [1.03224292 1.11676302 1.10623307 1.98137287 1.67601116]
  [1.01701779 1.73777258 1.90392873 1.80898349 1.11141536]]

 [[1.59211324 1.97018936 1.12910177 1.29515052 1.71266714]
  [1.75119378 1.80203319 1.58854164 1.70369114 1.61085821]
  [1.92919861 1.01558343 1.11564075 1.33505908 1.70180552]]]


#12. Multiply a and c. Assign the result to e.

In [117]:
e = a * c

e

array([[[0.11020846, 0.47331585, 0.76997304, 0.03925686, 0.2131871 ],
        [0.03224292, 0.11676302, 0.10623307, 0.98137287, 0.67601116],
        [0.01701779, 0.73777258, 0.90392873, 0.80898349, 0.11141536]],

       [[0.59211324, 0.97018936, 0.12910177, 0.29515052, 0.71266714],
        [0.75119378, 0.80203319, 0.58854164, 0.70369114, 0.61085821],
        [0.92919861, 0.01558343, 0.11564075, 0.33505908, 0.70180552]]])

#13. Does e equal to a? Why or why not?

#14. Identify the max, min, and mean values in d. Assign those values to variables "d_max","d_min", and "d_mean"

In [118]:
d_max = d.max()

d_min = d.min()

d_mean = d.mean()

#15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.


In [119]:
d.shape

(2, 3, 5)

In [120]:
f = np.empty([2, 3, 5])

In [121]:
f = np.empty(d.shape)
f.shape

(2, 3, 5)

#16. Populate the values in f. 
For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.

If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.

If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.

Assign 100 to the corresponding value(s) in f for d_max in d.

In the end, f should have only the following values: 0, 25, 50, 75, and 100.

Note: you don't have to use Numpy in this question.

In [123]:
for i in range(d.shape[0]):
    for j in range(d.shape[1]):
        for k in range(d.shape[2]):
            
            valor_f = d[i, j, k]
            
            if d_min < d [i, j, k] < d_mean:
                f[i, j, k] = 25
            elif d_mean < d [i, j, k] < d_max:
                f[i, j, k] = 75
            elif valor_f == d_mean:
                f[i, j, k] = 50
            elif d [i, j, k] == d_min:
                f[i, j, k] = 0
            elif d [i, j, k] == d_max:
                f[i, j, k] = 100

f

array([[[ 25.,  25.,  75.,  25.,  25.],
        [ 25.,  25.,  25., 100.,  75.],
        [ 25.,  75.,  75.,  75.,  25.]],

       [[ 75.,  75.,  25.,  25.,  75.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 75.,   0.,  25.,  25.,  75.]]])

In [124]:
print (d)

[[[1.11020846 1.47331585 1.76997304 1.03925686 1.2131871 ]
  [1.03224292 1.11676302 1.10623307 1.98137287 1.67601116]
  [1.01701779 1.73777258 1.90392873 1.80898349 1.11141536]]

 [[1.59211324 1.97018936 1.12910177 1.29515052 1.71266714]
  [1.75119378 1.80203319 1.58854164 1.70369114 1.61085821]
  [1.92919861 1.01558343 1.11564075 1.33505908 1.70180552]]]


In [125]:
print(f)

[[[ 25.  25.  75.  25.  25.]
  [ 25.  25.  25. 100.  75.]
  [ 25.  75.  75.  75.  25.]]

 [[ 75.  75.  25.  25.  75.]
  [ 75.  75.  75.  75.  75.]
  [ 75.   0.  25.  25.  75.]]]
