In [100]:
#1. Import the NUMPY package under the name np.
import numpy as np


In [101]:
#2. Print the NUMPY version and the configuration.
print(np.__version__)
print(np.show_config())



1.26.0
{
  "Compilers": {
    "c": {
      "name": "clang",
      "linker": "ld64",
      "version": "14.0.0",
      "commands": "clang"
    },
    "cython": {
      "name": "cython",
      "linker": "cython",
      "version": "3.0.2",
      "commands": "cython"
    },
    "c++": {
      "name": "clang",
      "linker": "ld64",
      "version": "14.0.0",
      "commands": "clang++"
    }
  },
  "Machine Information": {
    "host": {
      "cpu": "x86_64",
      "family": "x86_64",
      "endian": "little",
      "system": "darwin"
    },
    "build": {
      "cpu": "x86_64",
      "family": "x86_64",
      "endian": "little",
      "system": "darwin"
    }
  },
  "Build Dependencies": {
    "blas": {
      "name": "openblas64",
      "found": true,
      "version": "0.3.23.dev",
      "detection method": "pkgconfig",
      "include directory": "/usr/local/include",
      "lib directory": "/usr/local/lib",
      "openblas configuration": "USE_64BITINT=1 DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_

In [102]:
#3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
# Challenge: there are at least three easy ways that use numpy to generate random arrays. 
#How many ways can you find?


In [103]:
a = (np.random.random((2, 3, 5)))
a1 = (np.random.randint((2, 3, 5)))
a2 = (np.random.ranf((2, 3, 5)))

In [104]:
#4. Print a.
print(a)

[[[0.42797835 0.94527072 0.85217735 0.31471081 0.57127845]
  [0.78888229 0.47556318 0.14432664 0.86043615 0.81091317]
  [0.65891332 0.58938559 0.44498645 0.71055544 0.58479276]]

 [[0.03162433 0.03202645 0.02841003 0.9329019  0.08985258]
  [0.65794714 0.61763972 0.94234329 0.23972346 0.05073925]
  [0.29128889 0.79782445 0.31364049 0.10313579 0.54950451]]]


In [105]:
#5. Create a 5x2x3 3-dimensional array with all values equaling 1.
#Assign the array to variable "b"
b = np.ones((5, 2, 3))

In [106]:
#6. Print b.
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


In [107]:
#7. Do a and b have the same size? How do you prove that in Python code?
(a.size)==(b.size)

True

#8. Are you able to add a and b? Why or why not?
Nope. No se pueden sumar matrices con diferentes dimensiones

In [108]:
#9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). 
#Assign the transposed array to varialbe "c".
#c=(b.reshape(2, 3, 5))
c = np.transpose(b,(1, 2, 0))
print(c)
c.shape

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


(2, 3, 5)

In [109]:
#10. Try to add a and c. Now it should work. Assign the sum to varialbe "d". 
#But why does it work now?
d = (a+c)
#Porque las dimensiones de las matrices a sumar coinciden

In [114]:
#11. Print a and d. 
#Notice the difference and relation of the two array in terms of the values? Explain.
#Los valores de la matriz d son iguales a los de la a +1
print(a)
print(d)

[[[0.42797835 0.94527072 0.85217735 0.31471081 0.57127845]
  [0.78888229 0.47556318 0.14432664 0.86043615 0.81091317]
  [0.65891332 0.58938559 0.44498645 0.71055544 0.58479276]]

 [[0.03162433 0.03202645 0.02841003 0.9329019  0.08985258]
  [0.65794714 0.61763972 0.94234329 0.23972346 0.05073925]
  [0.29128889 0.79782445 0.31364049 0.10313579 0.54950451]]]
[[[1.42797835 1.94527072 1.85217735 1.31471081 1.57127845]
  [1.78888229 1.47556318 1.14432664 1.86043615 1.81091317]
  [1.65891332 1.58938559 1.44498645 1.71055544 1.58479276]]

 [[1.03162433 1.03202645 1.02841003 1.9329019  1.08985258]
  [1.65794714 1.61763972 1.94234329 1.23972346 1.05073925]
  [1.29128889 1.79782445 1.31364049 1.10313579 1.54950451]]]


In [115]:
#12. Multiply a and c. Assign the result to e.
e = (a*c)

In [116]:
##13. Does e equal to a? Why or why not?
#Porque e es el resultado de multiplicar los valores a * c y todos los valores de c son 1
(e.size)==(a.size)

True

In [117]:
#14. Identify the max, min, and mean values in d. 
#Assign those values to variables "d_max", "d_min", and "d_mean"
d_max = d.max()
d_min = d.min()
d_mean = d.mean()

In [118]:
#15. Now we want to label the values in d. 
#First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.
f = np.empty((2,3,5))
f

array([[[0.42797835, 0.94527072, 0.85217735, 0.31471081, 0.57127845],
        [0.78888229, 0.47556318, 0.14432664, 0.86043615, 0.81091317],
        [0.65891332, 0.58938559, 0.44498645, 0.71055544, 0.58479276]],

       [[0.03162433, 0.03202645, 0.02841003, 0.9329019 , 0.08985258],
        [0.65794714, 0.61763972, 0.94234329, 0.23972346, 0.05073925],
        [0.29128889, 0.79782445, 0.31364049, 0.10313579, 0.54950451]]])

In [119]:
"""
#16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.
"""

for i in range(d.shape[0]):
    for j in range(d.shape[1]):
        for k in range(d.shape[2]):
            if d_min < d[i, j, k] < d_mean:
                f[i, j, k] = 25
            elif d_mean < d[i, j, k] < d_max:
                f[i, j, k] = 75
            elif d[i, j, k] == d_mean:
                f[i, j, k] = 50
            elif d[i, j, k] == d_min:
                f[i, j, k] = 0
            elif d[i, j, k] == d_max:
                f[i, j, k] = 100
print(f)

[[[ 25. 100.  75.  25.  75.]
  [ 75.  25.  25.  75.  75.]
  [ 75.  75.  25.  75.  75.]]

 [[ 25.  25.   0.  75.  25.]
  [ 75.  75.  75.  25.  25.]
  [ 25.  75.  25.  25.  75.]]]


In [120]:
#17. Print d and f. Do you have your expected f?
print(d)
print(f)

"""For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])
"""


"""
#18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.
"""

[[[1.42797835 1.94527072 1.85217735 1.31471081 1.57127845]
  [1.78888229 1.47556318 1.14432664 1.86043615 1.81091317]
  [1.65891332 1.58938559 1.44498645 1.71055544 1.58479276]]

 [[1.03162433 1.03202645 1.02841003 1.9329019  1.08985258]
  [1.65794714 1.61763972 1.94234329 1.23972346 1.05073925]
  [1.29128889 1.79782445 1.31364049 1.10313579 1.54950451]]]
[[[ 25. 100.  75.  25.  75.]
  [ 75.  25.  25.  75.  75.]
  [ 75.  75.  25.  75.  75.]]

 [[ 25.  25.   0.  75.  25.]
  [ 75.  75.  75.  25.  25.]
  [ 25.  75.  25.  25.  75.]]]


'\n#18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values \n("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:\narray([[[ \'D\',  \'D\',  \'D\',  \'B\',  \'D\'],\n        [ \'D\',  \'D\',  \'B\',  \'B\',  \'B\'],\n        [ \'D\',  \'B\',  \'D\',  \'D\',  \'D\']],\n\n       [[ \'B\',  \'B\',  \'B\',  \'B\',  \'E\'],\n        [ \'D\',  \'D\',  \'D\',  \'D\',  \'D\'],\n        [ \'B\',  \'D\',   \'A\',  \'D\', \'D\']]])\nAgain, you don\'t need Numpy in this question.\n'