# 1. Import the NUMPY package under the name np.

In [1]:
import numpy as np

# 2. Print the NUMPY version and the configuration.

In [2]:
print(np.__version__)
print(np.show_config())

1.24.3
blas_armpl_info:
  NOT AVAILABLE
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/daarr/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/daarr/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/daarr/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/daarr/anaconda3\\Library\\include']
lapack_armpl_info:
  NOT AVAILABLE
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/daarr/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/daarr/anaconda3\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/daarr/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/daarr/anacond

# 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
# Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [3]:
a = np.random.random((2,3,5))

# 4. Print a.

In [4]:
print(a)

[[[0.09213387 0.56538303 0.63610446 0.48863496 0.08427164]
  [0.73527577 0.78760596 0.95055863 0.47502089 0.49344151]
  [0.9098705  0.86860998 0.43195881 0.45826046 0.22683416]]

 [[0.25233895 0.47321129 0.27272527 0.13384207 0.05838221]
  [0.51363645 0.68364015 0.93775745 0.07115538 0.45225659]
  [0.9980621  0.18003926 0.3998701  0.73560706 0.91738262]]]


# 5. Create a 5x2x3 3-dimensional array with all values equaling 1.
# Assign the array to variable "b"

In [5]:
b = np.ones((5,2,3))

# 6. Print b.

In [6]:
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


# 7. Do a and b have the same size? How do you prove that in Python code?

In [7]:
print(a.size == b.size)

True


# 8. Are you able to add a and b? Why or why not?

In [8]:
#NO, porque no tienen la misma forma/ "lens"

# 9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".

In [13]:
c = b.transpose((1,2,0))
print(c)

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


# 10. Try to add a and c. Now it should work. Assign the sum to varialbe "d". But why does it work now?

In [16]:
d = np.add(a,c)
d

array([[[1.09213387, 1.56538303, 1.63610446, 1.48863496, 1.08427164],
        [1.73527577, 1.78760596, 1.95055863, 1.47502089, 1.49344151],
        [1.9098705 , 1.86860998, 1.43195881, 1.45826046, 1.22683416]],

       [[1.25233895, 1.47321129, 1.27272527, 1.13384207, 1.05838221],
        [1.51363645, 1.68364015, 1.93775745, 1.07115538, 1.45225659],
        [1.9980621 , 1.18003926, 1.3998701 , 1.73560706, 1.91738262]]])

# 11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.

In [19]:
print(a)
print(d)
# Los valores de "d", son los de a sumándoles 1


[[[0.09213387 0.56538303 0.63610446 0.48863496 0.08427164]
  [0.73527577 0.78760596 0.95055863 0.47502089 0.49344151]
  [0.9098705  0.86860998 0.43195881 0.45826046 0.22683416]]

 [[0.25233895 0.47321129 0.27272527 0.13384207 0.05838221]
  [0.51363645 0.68364015 0.93775745 0.07115538 0.45225659]
  [0.9980621  0.18003926 0.3998701  0.73560706 0.91738262]]]
[[[1.09213387 1.56538303 1.63610446 1.48863496 1.08427164]
  [1.73527577 1.78760596 1.95055863 1.47502089 1.49344151]
  [1.9098705  1.86860998 1.43195881 1.45826046 1.22683416]]

 [[1.25233895 1.47321129 1.27272527 1.13384207 1.05838221]
  [1.51363645 1.68364015 1.93775745 1.07115538 1.45225659]
  [1.9980621  1.18003926 1.3998701  1.73560706 1.91738262]]]


# 12. Multiply a and c. Assign the result to e.

In [20]:
e = np.multiply(a,c)
e

array([[[0.09213387, 0.56538303, 0.63610446, 0.48863496, 0.08427164],
        [0.73527577, 0.78760596, 0.95055863, 0.47502089, 0.49344151],
        [0.9098705 , 0.86860998, 0.43195881, 0.45826046, 0.22683416]],

       [[0.25233895, 0.47321129, 0.27272527, 0.13384207, 0.05838221],
        [0.51363645, 0.68364015, 0.93775745, 0.07115538, 0.45225659],
        [0.9980621 , 0.18003926, 0.3998701 , 0.73560706, 0.91738262]]])

# 13. Does e equal to a? Why or why not?

In [22]:
#Sí, los valores de "e" son identicos que los de "a", ya que se han obtenido multiplicándolos *1

# 14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"

In [24]:
d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)
#print(d_max)
#print(d_min)
#print(d_mean)

# 15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.

In [33]:
f = np.empty((2,3,5))
print(f)

[[[0.09213387 0.56538303 0.63610446 0.48863496 0.08427164]
  [0.73527577 0.78760596 0.95055863 0.47502089 0.49344151]
  [0.9098705  0.86860998 0.43195881 0.45826046 0.22683416]]

 [[0.25233895 0.47321129 0.27272527 0.13384207 0.05838221]
  [0.51363645 0.68364015 0.93775745 0.07115538 0.45225659]
  [0.9980621  0.18003926 0.3998701  0.73560706 0.91738262]]]


# 16. Populate the values in f.

 For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
 
 If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
 
 If a value equals to d_mean, assign 50 to the corresponding value in f.
 
 Assign 0 to the corresponding value(s) in f for d_min in d.
 
 Assign 100 to the corresponding value(s) in f for d_max in d.
 
 In the end, f should have only the following values: 0, 25, 50, 75, and 100.
 
 Note: you don't have to use Numpy in this question.

In [37]:
for i, cubo in enumerate(d):
    for j, matriz in enumerate(cubo):
        for k, ele in enumerate(matriz):
            if (ele > d_min) and (ele < d_mean) :
                f[i][j][k] = 25
            elif (ele > d_mean) and (ele < d_max) :
                f[i][j][k] = 75
            elif (ele == d_mean):
                f[i][j][k] = 50
            elif (ele == d_min):
                f[i][j][k] = 0
            elif (ele == d_max):
                f[i][j][k] = 100
            else:
                pass
f

array([[[ 25.,  75.,  75.,  25.,  25.],
        [ 75.,  75.,  75.,  25.,  25.],
        [ 75.,  75.,  25.,  25.,  25.]],

       [[ 25.,  25.,  25.,  25.,   0.],
        [ 75.,  75.,  75.,  25.,  25.],
        [100.,  25.,  25.,  75.,  75.]]])

# 17. Print d and f. Do you have your expected f?

In [38]:
print(d, "\n", f)

[[[1.09213387 1.56538303 1.63610446 1.48863496 1.08427164]
  [1.73527577 1.78760596 1.95055863 1.47502089 1.49344151]
  [1.9098705  1.86860998 1.43195881 1.45826046 1.22683416]]

 [[1.25233895 1.47321129 1.27272527 1.13384207 1.05838221]
  [1.51363645 1.68364015 1.93775745 1.07115538 1.45225659]
  [1.9980621  1.18003926 1.3998701  1.73560706 1.91738262]]] 
 [[[ 25.  75.  75.  25.  25.]
  [ 75.  75.  75.  25.  25.]
  [ 75.  75.  25.  25.  25.]]

 [[ 25.  25.  25.  25.   0.]
  [ 75.  75.  75.  25.  25.]
  [100.  25.  25.  75.  75.]]]


# 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array( [

        [[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],
        
        [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.
"""

In [40]:
f = f.astype(str)
for i, cubo in enumerate(d):
    for j, matriz in enumerate(cubo):
        for k, ele in enumerate(matriz):
            if (ele > d_min) and (ele < d_mean) :
                f[i][j][k] = "B"
            elif (ele > d_mean) and (ele < d_max) :
                f[i][j][k] = "D"
            elif (ele == d_mean):
                f[i][j][k] = "C"
            elif (ele == d_min):
                f[i][j][k] = "A"
            elif (ele == d_max):
                f[i][j][k] = "E"
            else:
                pass
f

array([[['B', 'D', 'D', 'B', 'B'],
        ['D', 'D', 'D', 'B', 'B'],
        ['D', 'D', 'B', 'B', 'B']],

       [['B', 'B', 'B', 'B', 'A'],
        ['D', 'D', 'D', 'B', 'B'],
        ['E', 'B', 'B', 'D', 'D']]], dtype='<U32')