In [1]:
#1. Import the NUMPY package under the name np.

import numpy as np


#2. Print the NUMPY version and the configuration.

# print("Numpy version: ",np.__version__ )
# print("Numpy configuration: ",np.show_config())

In [2]:
a = np.random.rand(2,3,5)

In [3]:
a = np.random.random_sample((2,3,5))

In [4]:
low = 0
high = 1

a = np.random.uniform(low,high,(2,3,5))

In [5]:
print(a)

[[[0.15529341 0.26226673 0.3421019  0.82050661 0.15848506]
  [0.87955189 0.05435046 0.86784089 0.96847385 0.05835783]
  [0.17861743 0.12802595 0.75727694 0.92373701 0.55987738]]

 [[0.96627163 0.49035433 0.52968988 0.54833908 0.89024577]
  [0.42266557 0.07379123 0.25823347 0.19119812 0.39762479]
  [0.84270017 0.22801707 0.30569525 0.17809554 0.72845428]]]


In [6]:
b = np.ones((5,2,3))

In [7]:
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


In [8]:
np.size(a) == np.size(b)

# we use the np.size function to check if both arrays have the same total number of elements

True

In [9]:
# No podemos sumar los arrays a y b debido a que tienen tamaños incompatibles.
# Para sumar arrays deben tener el mismo número de dimensiones
# El tamaño de las dimensiones deben ser iguales o una debe ser long 1

# para sumar los arrays dados se puede modificar el tamaño de uno de ellos:
# a_nuevo = a.reshape(5,2,3)
# c = a_nuevo + b

In [10]:
c = b.reshape(2,3,5)

In [11]:
d = a + c
# Ahora podemos sumar ambos arrays debido a que cumplen las normas del tamaño

In [12]:
print(a,d)

# El array d es el resultado de añadir los valores 1 del array b a los valores aleatorios de a

[[[0.15529341 0.26226673 0.3421019  0.82050661 0.15848506]
  [0.87955189 0.05435046 0.86784089 0.96847385 0.05835783]
  [0.17861743 0.12802595 0.75727694 0.92373701 0.55987738]]

 [[0.96627163 0.49035433 0.52968988 0.54833908 0.89024577]
  [0.42266557 0.07379123 0.25823347 0.19119812 0.39762479]
  [0.84270017 0.22801707 0.30569525 0.17809554 0.72845428]]] [[[1.15529341 1.26226673 1.3421019  1.82050661 1.15848506]
  [1.87955189 1.05435046 1.86784089 1.96847385 1.05835783]
  [1.17861743 1.12802595 1.75727694 1.92373701 1.55987738]]

 [[1.96627163 1.49035433 1.52968988 1.54833908 1.89024577]
  [1.42266557 1.07379123 1.25823347 1.19119812 1.39762479]
  [1.84270017 1.22801707 1.30569525 1.17809554 1.72845428]]]


In [13]:
e = a * c
print(e)

[[[0.15529341 0.26226673 0.3421019  0.82050661 0.15848506]
  [0.87955189 0.05435046 0.86784089 0.96847385 0.05835783]
  [0.17861743 0.12802595 0.75727694 0.92373701 0.55987738]]

 [[0.96627163 0.49035433 0.52968988 0.54833908 0.89024577]
  [0.42266557 0.07379123 0.25823347 0.19119812 0.39762479]
  [0.84270017 0.22801707 0.30569525 0.17809554 0.72845428]]]


In [14]:
e == a
# el array e es igual al array a debido a que estamos multiplicando de forma element-wise 
# al multiplicar elemento a elemento y siendo el array c todo unos
# las operaciones que se realizan son cada elemento de e * 1

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

In [15]:
d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)

In [16]:
print("max",d_max)
print("min",d_min)
print("mean",d_mean)

max 1.968473846148446
min 1.0543504639789503
mean 1.4722046509085716


In [17]:
f = np.zeros(d.shape)

In [18]:
for i in range(d.shape[0]):
    for j in range(d.shape[1]):
        for k in range(d.shape[2]):
            value = d[i, j, k]
            if value == d_mean:
                f[i, j, k] = 50
            elif value > d_min and value < d_mean:
                f[i, j, k] = 25
            elif value > d_mean and value < d_max:
                f[i, j, k] = 75
            elif value == d_min:
                f[i, j, k] = 0
            elif value == d_max:
                f[i, j, k] = 100

print(f)

[[[ 25.  25.  25.  75.  25.]
  [ 75.   0.  75. 100.  25.]
  [ 25.  25.  75.  75.  75.]]

 [[ 75.  75.  75.  75.  75.]
  [ 25.  25.  25.  25.  25.]
  [ 75.  25.  25.  25.  75.]]]


In [19]:
g = np.empty(d.shape,dtype=object)

for i in range(d.shape[0]):
    for j in range(d.shape[1]):
        for k in range(d.shape[2]):
            value = d[i,j,k]
            if value == d_mean:
                g[i,j,k] = 'C'
            elif value > d_min and value < d_mean:
                g[i,j,k] = 'B'
            elif value > d_mean and value < d_max:
                g[i,j,k] = 'D'
            elif value == d_min:
                g[i,j,k] = 'A'
            elif value == d_max:
                g[i,j,k] = 'E'


print(g)

[[['B' 'B' 'B' 'D' 'B']
  ['D' 'A' 'D' 'E' 'B']
  ['B' 'B' 'D' 'D' 'D']]

 [['D' 'D' 'D' 'D' 'D']
  ['B' 'B' 'B' 'B' 'B']
  ['D' 'B' 'B' 'B' 'D']]]
