#1. Import the NUMPY package under the name np.

In [1]:
import numpy as np

#2. Print the NUMPY version and the configuration.

In [2]:
print(np.__version__)

1.24.3


In [3]:
print(np.show_config())

blas_armpl_info:
  NOT AVAILABLE
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/ccior/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/ccior/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/ccior/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/ccior/anaconda3\\Library\\include']
lapack_armpl_info:
  NOT AVAILABLE
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/ccior/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/ccior/anaconda3\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/ccior/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/ccior/anaconda3\\Lib

In [4]:
#3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
# Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [5]:
a = np.random.random((2, 3, 5))   # 10 filas, 4 columnas

a

array([[[0.41544828, 0.90882336, 0.84294781, 0.12565439, 0.95329379],
        [0.82347037, 0.12463845, 0.81492178, 0.45369349, 0.62770048],
        [0.39370667, 0.80442774, 0.78657717, 0.46966898, 0.39583959]],

       [[0.24744778, 0.29967457, 0.54212891, 0.95743644, 0.91579212],
        [0.40178677, 0.75030727, 0.00126251, 0.31483582, 0.07234888],
        [0.16592991, 0.36788234, 0.75316316, 0.27270528, 0.18728539]]])

#4. Print a.

In [6]:
print(a)

[[[0.41544828 0.90882336 0.84294781 0.12565439 0.95329379]
  [0.82347037 0.12463845 0.81492178 0.45369349 0.62770048]
  [0.39370667 0.80442774 0.78657717 0.46966898 0.39583959]]

 [[0.24744778 0.29967457 0.54212891 0.95743644 0.91579212]
  [0.40178677 0.75030727 0.00126251 0.31483582 0.07234888]
  [0.16592991 0.36788234 0.75316316 0.27270528 0.18728539]]]


#5. Create a 5x2x3 3-dimensional array with all values equaling 1.
#Assign the array to variable "b"

In [7]:
b = np.random.random((5,2,3))

b

array([[[0.25127728, 0.02432848, 0.7835425 ],
        [0.05353644, 0.95747567, 0.78608743]],

       [[0.54244471, 0.24386179, 0.90087486],
        [0.61690017, 0.35889265, 0.91021196]],

       [[0.8105616 , 0.85787038, 0.75677222],
        [0.41754265, 0.21105828, 0.9405565 ]],

       [[0.39444712, 0.10499986, 0.09587366],
        [0.2323715 , 0.09188882, 0.04013125]],

       [[0.53842892, 0.43092237, 0.63618114],
        [0.60574168, 0.1665205 , 0.95896981]]])

#6. Print b.

In [8]:
print(b)

[[[0.25127728 0.02432848 0.7835425 ]
  [0.05353644 0.95747567 0.78608743]]

 [[0.54244471 0.24386179 0.90087486]
  [0.61690017 0.35889265 0.91021196]]

 [[0.8105616  0.85787038 0.75677222]
  [0.41754265 0.21105828 0.9405565 ]]

 [[0.39444712 0.10499986 0.09587366]
  [0.2323715  0.09188882 0.04013125]]

 [[0.53842892 0.43092237 0.63618114]
  [0.60574168 0.1665205  0.95896981]]]


#7. Do a and b have the same size? How do you prove that in Python code?

In [9]:
def shape_of_you(a,b):
    
    if a.shape == b.shape:
        return True
    else:
        return False

In [10]:
shape_of_you(a,b)

False

#8. Are you able to add a and b? Why or why not?

In [12]:
c = a + b

c

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

In [13]:
#both arrays need to have the same shape

#9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".

In [14]:
c = a + b.transpose((1,2,0))

print(c)

[[[0.66672555 1.45126808 1.65350941 0.52010152 1.49172271]
  [0.84779885 0.36850024 1.67279216 0.55869334 1.05862285]
  [1.17724917 1.7053026  1.54334939 0.56554264 1.03202074]]

 [[0.30098422 0.91657475 0.95967156 1.18980794 1.5215338 ]
  [1.35926244 1.10919992 0.21232079 0.40672465 0.23886938]
  [0.95201734 1.2780943  1.69371966 0.31283654 1.1462552 ]]]


In [15]:
#10. Try to add a and c. Now it should work. Assign the sum to varialbe "d". But why does it work now?

In [16]:
d = a + c

print(d)

[[[1.08217383 2.36009144 2.49645722 0.64575591 2.44501649]
  [1.67126922 0.49313869 2.48771394 1.01238683 1.68632332]
  [1.57095584 2.50973034 2.32992656 1.03521161 1.42786033]]

 [[0.54843201 1.21624932 1.50180047 2.14724438 2.43732592]
  [1.76104922 1.85950719 0.2135833  0.72156047 0.31121826]
  [1.11794725 1.64597664 2.44688282 0.58554182 1.33354059]]]


In [17]:
#it works because a and c have the same shape

#12. Multiply a and c. Assign the result to e.

In [18]:
e = a * c
print(e)

[[[2.76989982e-01 1.31894633e+00 1.39382214e+00 6.53530405e-02
   1.42204999e+00]
  [6.98137236e-01 4.59292994e-02 1.36319477e+00 2.53475531e-01
   6.64498065e-01]
  [4.63490847e-01 1.37179272e+00 1.21396340e+00 2.65617832e-01
   4.08514668e-01]]

 [[7.44778792e-02 2.74674147e-01 5.20265698e-01 1.13916548e+00
   1.39340866e+00]
  [5.46133668e-01 8.32240762e-01 2.68056963e-04 1.28051488e-01
   1.72819324e-02]
  [1.57968154e-01 4.70188323e-01 1.27564725e+00 8.53121751e-02
   2.14676848e-01]]]


#13. Does e equal to a? Why or why not?

In [19]:
e == a

array([[[False, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False]],

       [[False, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False]]])

#14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"

In [20]:
d_max = d.max()
d_min = d.min()
d_mean = d.mean()

#15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.import numpy as np

In [21]:
import numpy as np

f = np.empty((2, 3, 5))
print(f)

[[[2.76989982e-01 1.31894633e+00 1.39382214e+00 6.53530405e-02
   1.42204999e+00]
  [6.98137236e-01 4.59292994e-02 1.36319477e+00 2.53475531e-01
   6.64498065e-01]
  [4.63490847e-01 1.37179272e+00 1.21396340e+00 2.65617832e-01
   4.08514668e-01]]

 [[7.44778792e-02 2.74674147e-01 5.20265698e-01 1.13916548e+00
   1.39340866e+00]
  [5.46133668e-01 8.32240762e-01 2.68056963e-04 1.28051488e-01
   1.72819324e-02]
  [1.57968154e-01 4.70188323e-01 1.27564725e+00 8.53121751e-02
   2.14676848e-01]]]


#16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.

If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.

If a value equals to d_mean, assign 50 to the corresponding value in f.

Assign 0 to the corresponding value(s) in f for d_min in d.

Assign 100 to the corresponding value(s) in f for d_max in d.

In the end, f should have only the following values: 0, 25, 50, 75, and 100.
    
Note: you don't have to use Numpy in this question.

In [22]:
print(f)

[[[2.76989982e-01 1.31894633e+00 1.39382214e+00 6.53530405e-02
   1.42204999e+00]
  [6.98137236e-01 4.59292994e-02 1.36319477e+00 2.53475531e-01
   6.64498065e-01]
  [4.63490847e-01 1.37179272e+00 1.21396340e+00 2.65617832e-01
   4.08514668e-01]]

 [[7.44778792e-02 2.74674147e-01 5.20265698e-01 1.13916548e+00
   1.39340866e+00]
  [5.46133668e-01 8.32240762e-01 2.68056963e-04 1.28051488e-01
   1.72819324e-02]
  [1.57968154e-01 4.70188323e-01 1.27564725e+00 8.53121751e-02
   2.14676848e-01]]]


In [23]:
#For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.

f = np.where((d > d_min) & (d < d_mean), 25, f)
print(f)

[[[2.50000000e+01 1.31894633e+00 1.39382214e+00 2.50000000e+01
   1.42204999e+00]
  [6.98137236e-01 2.50000000e+01 1.36319477e+00 2.50000000e+01
   6.64498065e-01]
  [4.63490847e-01 1.37179272e+00 1.21396340e+00 2.50000000e+01
   2.50000000e+01]]

 [[2.50000000e+01 2.50000000e+01 2.50000000e+01 1.13916548e+00
   1.39340866e+00]
  [5.46133668e-01 8.32240762e-01 2.68056963e-04 2.50000000e+01
   2.50000000e+01]
  [2.50000000e+01 4.70188323e-01 1.27564725e+00 2.50000000e+01
   2.50000000e+01]]]


In [24]:
#If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f

f = np.where((d > d_mean) & (d < d_max), 75, f)
print(f)

[[[2.50000000e+01 7.50000000e+01 7.50000000e+01 2.50000000e+01
   7.50000000e+01]
  [7.50000000e+01 2.50000000e+01 7.50000000e+01 2.50000000e+01
   7.50000000e+01]
  [7.50000000e+01 1.37179272e+00 7.50000000e+01 2.50000000e+01
   2.50000000e+01]]

 [[2.50000000e+01 2.50000000e+01 2.50000000e+01 7.50000000e+01
   7.50000000e+01]
  [7.50000000e+01 7.50000000e+01 2.68056963e-04 2.50000000e+01
   2.50000000e+01]
  [2.50000000e+01 7.50000000e+01 7.50000000e+01 2.50000000e+01
   2.50000000e+01]]]


In [25]:
#If a value equals to d_mean, assign 50 to the corresponding value in f.

f = np.where(d == d_mean, 50, f)
print(f)

[[[2.50000000e+01 7.50000000e+01 7.50000000e+01 2.50000000e+01
   7.50000000e+01]
  [7.50000000e+01 2.50000000e+01 7.50000000e+01 2.50000000e+01
   7.50000000e+01]
  [7.50000000e+01 1.37179272e+00 7.50000000e+01 2.50000000e+01
   2.50000000e+01]]

 [[2.50000000e+01 2.50000000e+01 2.50000000e+01 7.50000000e+01
   7.50000000e+01]
  [7.50000000e+01 7.50000000e+01 2.68056963e-04 2.50000000e+01
   2.50000000e+01]
  [2.50000000e+01 7.50000000e+01 7.50000000e+01 2.50000000e+01
   2.50000000e+01]]]


In [26]:
#Assign 0 to the corresponding value(s) in f for d_min in d

f = np.where(d == d_min, 0, f)
print(f)

[[[25.         75.         75.         25.         75.        ]
  [75.         25.         75.         25.         75.        ]
  [75.          1.37179272 75.         25.         25.        ]]

 [[25.         25.         25.         75.         75.        ]
  [75.         75.          0.         25.         25.        ]
  [25.         75.         75.         25.         25.        ]]]


In [27]:
#Assign 100 to the corresponding value(s) in f for d_max in d.

f = np.where(d == d_max, 100, f)
print(f)

[[[ 25.  75.  75.  25.  75.]
  [ 75.  25.  75.  25.  75.]
  [ 75. 100.  75.  25.  25.]]

 [[ 25.  25.  25.  75.  75.]
  [ 75.  75.   0.  25.  25.]
  [ 25.  75.  75.  25.  25.]]]


In [ ]:
#17. Print d and f. Do you have your expected f?

For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])

In [28]:
print(d)

[[[1.08217383 2.36009144 2.49645722 0.64575591 2.44501649]
  [1.67126922 0.49313869 2.48771394 1.01238683 1.68632332]
  [1.57095584 2.50973034 2.32992656 1.03521161 1.42786033]]

 [[0.54843201 1.21624932 1.50180047 2.14724438 2.43732592]
  [1.76104922 1.85950719 0.2135833  0.72156047 0.31121826]
  [1.11794725 1.64597664 2.44688282 0.58554182 1.33354059]]]


In [29]:
print(f)

[[[ 25.  75.  75.  25.  75.]
  [ 75.  25.  75.  25.  75.]
  [ 75. 100.  75.  25.  25.]]

 [[ 25.  25.  25.  75.  75.]
  [ 75.  75.   0.  25.  25.]
  [ 25.  75.  75.  25.  25.]]]


#18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.