# 1. Import the NUMPY package under the name np.

In [12]:
import numpy as np

# 2. Print the NUMPY version and the configuration.

In [13]:

np.__version__
np.show_config

<function numpy.__config__.show()>

# 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a". 
#Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [14]:
a = np.random.random((2,3,5))

# 4. Print a.

In [15]:
a

array([[[0.24736014, 0.05817055, 0.39014729, 0.08435554, 0.40301865],
        [0.32199163, 0.62998089, 0.02464037, 0.26956797, 0.98085014],
        [0.2704443 , 0.47974232, 0.03110858, 0.35056915, 0.38501023]],

       [[0.5796017 , 0.73249676, 0.7939184 , 0.06302726, 0.50331414],
        [0.30478309, 0.66832229, 0.05165797, 0.86216533, 0.26456163],
        [0.12093544, 0.80340527, 0.12272118, 0.07665269, 0.6769143 ]]])

# 5. Create a 5x2x3 3-dimensional array with all values equaling 1.
#Assign the array to variable "b"

In [16]:
b= np.ones((5,2,3))

# 6. Print b.

In [17]:
b

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

# 7. Do a and b have the same size? How do you prove that in Python code?

In [18]:
a.size

30

In [19]:
b.size

30

Sí, a y b tienen el mismo número de elementos.

# 8. Are you able to add a and b? Why or why not?

In [66]:
a

array([[[0.24736014, 0.05817055, 0.39014729, 0.08435554, 0.40301865],
        [0.32199163, 0.62998089, 0.02464037, 0.26956797, 0.98085014],
        [0.2704443 , 0.47974232, 0.03110858, 0.35056915, 0.38501023]],

       [[0.5796017 , 0.73249676, 0.7939184 , 0.06302726, 0.50331414],
        [0.30478309, 0.66832229, 0.05165797, 0.86216533, 0.26456163],
        [0.12093544, 0.80340527, 0.12272118, 0.07665269, 0.6769143 ]]])

In [67]:
b

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [68]:
a+b

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

No se pueden sumar ambas matrices ya que no comparten los mismos componentes. a= 2x3x5
b= 5x2x3

# 9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".

In [48]:
c= b.transpose((1,2,0))

In [49]:
c

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

# 10. Try to add a and c. Now it should work. Assign the sum to varialbe "d". But why does it work now?

In [56]:
d = a+c
print(d)
print(a)

[[[1.24736014 1.05817055 1.39014729 1.08435554 1.40301865]
  [1.32199163 1.62998089 1.02464037 1.26956797 1.98085014]
  [1.2704443  1.47974232 1.03110858 1.35056915 1.38501023]]

 [[1.5796017  1.73249676 1.7939184  1.06302726 1.50331414]
  [1.30478309 1.66832229 1.05165797 1.86216533 1.26456163]
  [1.12093544 1.80340527 1.12272118 1.07665269 1.6769143 ]]]
[[[0.24736014 0.05817055 0.39014729 0.08435554 0.40301865]
  [0.32199163 0.62998089 0.02464037 0.26956797 0.98085014]
  [0.2704443  0.47974232 0.03110858 0.35056915 0.38501023]]

 [[0.5796017  0.73249676 0.7939184  0.06302726 0.50331414]
  [0.30478309 0.66832229 0.05165797 0.86216533 0.26456163]
  [0.12093544 0.80340527 0.12272118 0.07665269 0.6769143 ]]]


Ahora si suma la matriz a con la matriz c, debido a que las dimensiones de las mismas son iguales.

# 11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.

In [57]:
a

array([[[0.24736014, 0.05817055, 0.39014729, 0.08435554, 0.40301865],
        [0.32199163, 0.62998089, 0.02464037, 0.26956797, 0.98085014],
        [0.2704443 , 0.47974232, 0.03110858, 0.35056915, 0.38501023]],

       [[0.5796017 , 0.73249676, 0.7939184 , 0.06302726, 0.50331414],
        [0.30478309, 0.66832229, 0.05165797, 0.86216533, 0.26456163],
        [0.12093544, 0.80340527, 0.12272118, 0.07665269, 0.6769143 ]]])

In [58]:
d

array([[[1.24736014, 1.05817055, 1.39014729, 1.08435554, 1.40301865],
        [1.32199163, 1.62998089, 1.02464037, 1.26956797, 1.98085014],
        [1.2704443 , 1.47974232, 1.03110858, 1.35056915, 1.38501023]],

       [[1.5796017 , 1.73249676, 1.7939184 , 1.06302726, 1.50331414],
        [1.30478309, 1.66832229, 1.05165797, 1.86216533, 1.26456163],
        [1.12093544, 1.80340527, 1.12272118, 1.07665269, 1.6769143 ]]])

In [59]:
np.array_equal(a,d)

False

La diferencia es que en la matriz a todos los elementos se le suman 1.

# 12. Multiply a and c. Assign the result to e.

In [60]:
e=a*c
e

array([[[0.24736014, 0.05817055, 0.39014729, 0.08435554, 0.40301865],
        [0.32199163, 0.62998089, 0.02464037, 0.26956797, 0.98085014],
        [0.2704443 , 0.47974232, 0.03110858, 0.35056915, 0.38501023]],

       [[0.5796017 , 0.73249676, 0.7939184 , 0.06302726, 0.50331414],
        [0.30478309, 0.66832229, 0.05165797, 0.86216533, 0.26456163],
        [0.12093544, 0.80340527, 0.12272118, 0.07665269, 0.6769143 ]]])

In [61]:
a

array([[[0.24736014, 0.05817055, 0.39014729, 0.08435554, 0.40301865],
        [0.32199163, 0.62998089, 0.02464037, 0.26956797, 0.98085014],
        [0.2704443 , 0.47974232, 0.03110858, 0.35056915, 0.38501023]],

       [[0.5796017 , 0.73249676, 0.7939184 , 0.06302726, 0.50331414],
        [0.30478309, 0.66832229, 0.05165797, 0.86216533, 0.26456163],
        [0.12093544, 0.80340527, 0.12272118, 0.07665269, 0.6769143 ]]])

# 13. Does e equal to a? Why or why not?

In [63]:
e

array([[[0.24736014, 0.05817055, 0.39014729, 0.08435554, 0.40301865],
        [0.32199163, 0.62998089, 0.02464037, 0.26956797, 0.98085014],
        [0.2704443 , 0.47974232, 0.03110858, 0.35056915, 0.38501023]],

       [[0.5796017 , 0.73249676, 0.7939184 , 0.06302726, 0.50331414],
        [0.30478309, 0.66832229, 0.05165797, 0.86216533, 0.26456163],
        [0.12093544, 0.80340527, 0.12272118, 0.07665269, 0.6769143 ]]])

In [64]:
a

array([[[0.24736014, 0.05817055, 0.39014729, 0.08435554, 0.40301865],
        [0.32199163, 0.62998089, 0.02464037, 0.26956797, 0.98085014],
        [0.2704443 , 0.47974232, 0.03110858, 0.35056915, 0.38501023]],

       [[0.5796017 , 0.73249676, 0.7939184 , 0.06302726, 0.50331414],
        [0.30478309, 0.66832229, 0.05165797, 0.86216533, 0.26456163],
        [0.12093544, 0.80340527, 0.12272118, 0.07665269, 0.6769143 ]]])

In [65]:
np.array_equal(e,a)

True

No son iguales, porque los valores en la primera matriz son diferentes de los valores en la segunda matriz.

# 14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"

# 15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.

# 16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.


In [ ]:
bucle 

# 17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])
        Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])

# 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.
"""