In [1]:
#1. Import the NUMPY package under the name np.
import numpy as np

In [2]:
#2. Print the NUMPY version and the configuration.
print("NumPy Version:", np.__version__)

NumPy Version: 1.24.3


In [4]:
print("NumPy Configuration:")
print(np.show_config())

NumPy Configuration:
blas_armpl_info:
  NOT AVAILABLE
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/Users/yaninafontana/anaconda3/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/Users/yaninafontana/anaconda3/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_armpl_info:
  NOT AVAILABLE
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/Users/yaninafontana/anaconda3/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/Users/yaninafontana/anaconda3/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
Supported SIMD extensions in this NumPy install:
    baseline = NEON,NEON_FP16,NEON_VFPV4,ASIMD
    found = ASIMDHP

In [57]:
#3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
# Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?
a = np.random.random((2, 3, 5))

In [58]:
#4. Print a.
a

array([[[0.38762927, 0.08082118, 0.67026023, 0.53695278, 0.60695801],
        [0.5024475 , 0.26538667, 0.28275931, 0.17678929, 0.07636075],
        [0.55228169, 0.46914096, 0.05308446, 0.16980104, 0.442888  ]],

       [[0.20077823, 0.76413664, 0.22832975, 0.03879249, 0.74896712],
        [0.04516452, 0.05401988, 0.79616755, 0.1598367 , 0.63887974],
        [0.22273537, 0.05686438, 0.38877344, 0.15708252, 0.69878296]]])

In [59]:
#5. Create a 5x2x3 3-dimensional array with all values equaling 1.
#Assign the array to variable "b"
b = np.ones((5, 2, 3))

In [60]:
#6. Print b.
b

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [61]:
#7. Do a and b have the same size? How do you prove that in Python code? si
a.size == b.size

True

In [62]:
#8. Are you able to add a and b? Why or why not?, 
#no, porque para sumar deben tener dimensiones iguales ya que se suma elemento a elemento

a + b

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

In [63]:
#9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). 
#Assign the transposed array to varialbe "c".
c = b.transpose(1, 2, 0)

In [64]:
c

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [65]:
a.shape == c.shape

True

In [66]:
#10. Try to add a and c. Now it should work. Assign the sum to varialbe "d". But why does it work now?
#Ahora si, porque tienen las mismas dimensiones
d = a + c

In [67]:
#11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain. 
# A cada valor de a se le sumó 1, que eran los valores de c, es decir de b.T
d

array([[[1.38762927, 1.08082118, 1.67026023, 1.53695278, 1.60695801],
        [1.5024475 , 1.26538667, 1.28275931, 1.17678929, 1.07636075],
        [1.55228169, 1.46914096, 1.05308446, 1.16980104, 1.442888  ]],

       [[1.20077823, 1.76413664, 1.22832975, 1.03879249, 1.74896712],
        [1.04516452, 1.05401988, 1.79616755, 1.1598367 , 1.63887974],
        [1.22273537, 1.05686438, 1.38877344, 1.15708252, 1.69878296]]])

In [68]:
#12. Multiply a and c. Assign the result to e.
e = a * c

In [69]:
e

array([[[0.38762927, 0.08082118, 0.67026023, 0.53695278, 0.60695801],
        [0.5024475 , 0.26538667, 0.28275931, 0.17678929, 0.07636075],
        [0.55228169, 0.46914096, 0.05308446, 0.16980104, 0.442888  ]],

       [[0.20077823, 0.76413664, 0.22832975, 0.03879249, 0.74896712],
        [0.04516452, 0.05401988, 0.79616755, 0.1598367 , 0.63887974],
        [0.22273537, 0.05686438, 0.38877344, 0.15708252, 0.69878296]]])

In [70]:
#13. Does e equal to a? Why or why not? si, porque 1 es el valor neutro en la multiplicación. 
#multiplicar un nro por 1, es igual a ese mismo número.
a == e

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

In [71]:
#14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"
d_max = np.max(d)
d_max

1.7961675477970274

In [72]:
d_min = np.min(d)
d_min

1.0387924927150944

In [73]:
d_mean = np.mean(d)
d_mean

1.349095746679343

In [74]:
#15. Now we want to label the values in d. 
#First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.
f = np.empty

In [75]:
f

<function numpy.empty>

In [85]:
#16. Populate the values in f. 
#For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
#If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
#If a value equals to d_mean, assign 50 to the corresponding value in f.
#Assign 0 to the corresponding value(s) in f for d_min in d.
#Assign 100 to the corresponding value(s) in f for d_max in d.
#In the end, f should have only the following values: 0, 25, 50, 75, and 100.
#Note: you don't have to use Numpy in this question.
#Valores de f
# Si element = d_min ==> 0
# Si d_min < element < d_mean ==> 25
# si element = d_mean ==> 50
# Si d_mean < element < d_max ==> 75
# Si element = d_max ==> 100

f = np.empty
f = np.where((d > d_min) & (d < d_mean), 25, 
             np.where((d > d_mean) & (d < d_max), 75, 
                      np.where(d == d_min, 0, 
                               np.where(d == d_mean, 50, 
                                        100))))


In [86]:
#17. Print d and f. Do you have your expected f?

In [87]:
d

array([[[1.38762927, 1.08082118, 1.67026023, 1.53695278, 1.60695801],
        [1.5024475 , 1.26538667, 1.28275931, 1.17678929, 1.07636075],
        [1.55228169, 1.46914096, 1.05308446, 1.16980104, 1.442888  ]],

       [[1.20077823, 1.76413664, 1.22832975, 1.03879249, 1.74896712],
        [1.04516452, 1.05401988, 1.79616755, 1.1598367 , 1.63887974],
        [1.22273537, 1.05686438, 1.38877344, 1.15708252, 1.69878296]]])

In [88]:
f

array([[[ 75,  25,  75,  75,  75],
        [ 75,  25,  25,  25,  25],
        [ 75,  75,  25,  25,  75]],

       [[ 25,  75,  25,   0,  75],
        [ 25,  25, 100,  25,  75],
        [ 25,  25,  75,  25,  75]]])

In [89]:
#18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
#("A", "B", "C", "D", and "E") to label the array elements? 

In [93]:
g = np.where((d > d_min) & (d < d_mean), 'B', 
               np.where((d > d_mean) & (d < d_max), 'D', 
                        np.where(d == d_min, 'A', 
                                 np.where(d == d_mean, 'C', 
                                          'E'))))
print(g)

[[['D' 'B' 'D' 'D' 'D']
  ['D' 'B' 'B' 'B' 'B']
  ['D' 'D' 'B' 'B' 'D']]

 [['B' 'D' 'B' 'A' 'D']
  ['B' 'B' 'E' 'B' 'D']
  ['B' 'B' 'D' 'B' 'D']]]
