In [3]:
#1. Import the NUMPY package under the name np.

%pip install numpy

import numpy as np

Note: you may need to restart the kernel to use updated packages.


In [4]:

#2. Print the NUMPY version and the configuration.

print(np. __version__)

1.24.3


In [5]:

#3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
# Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

a=np.random.random((2,3,5))

In [6]:

#4. Print a.

print(a)

[[[0.80616579 0.87630752 0.46481359 0.67912551 0.13200411]
  [0.79156378 0.22793445 0.18187254 0.34125704 0.31904492]
  [0.25473676 0.03580231 0.71275198 0.75110648 0.50934417]]

 [[0.40435043 0.38011305 0.73202142 0.66732849 0.76356686]
  [0.98673213 0.62082971 0.54097282 0.99770969 0.81250361]
  [0.09332444 0.25724727 0.50133725 0.1262348  0.77804693]]]


In [7]:

#5. Create a 5x2x3 3-dimensional array with all values equaling 1.
#Assign the array to variable "b"

b = np.ones((5,2,3))

b.shape

(5, 2, 3)

In [8]:

#6. Print b.

print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


In [9]:

#7. Do a and b have the same size? How do you prove that in Python code?

a.shape

(2, 3, 5)

In [10]:

#8. Are you able to add a and b? Why or why not?


# No se pueden sumar ya que las dimensiones deben ser iguales


In [11]:

#9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".

c=np.transpose(b, (1,2,0))

c.shape

(2, 3, 5)

In [12]:

#10. Try to add a and c. Now it should work. Assign the sum to varialbe "d". But why does it work now?

d= a+c

d


array([[[1.80616579, 1.87630752, 1.46481359, 1.67912551, 1.13200411],
        [1.79156378, 1.22793445, 1.18187254, 1.34125704, 1.31904492],
        [1.25473676, 1.03580231, 1.71275198, 1.75110648, 1.50934417]],

       [[1.40435043, 1.38011305, 1.73202142, 1.66732849, 1.76356686],
        [1.98673213, 1.62082971, 1.54097282, 1.99770969, 1.81250361],
        [1.09332444, 1.25724727, 1.50133725, 1.1262348 , 1.77804693]]])

In [13]:

#11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.

print(a)
print(d)

#los valores se han sumado

[[[0.80616579 0.87630752 0.46481359 0.67912551 0.13200411]
  [0.79156378 0.22793445 0.18187254 0.34125704 0.31904492]
  [0.25473676 0.03580231 0.71275198 0.75110648 0.50934417]]

 [[0.40435043 0.38011305 0.73202142 0.66732849 0.76356686]
  [0.98673213 0.62082971 0.54097282 0.99770969 0.81250361]
  [0.09332444 0.25724727 0.50133725 0.1262348  0.77804693]]]
[[[1.80616579 1.87630752 1.46481359 1.67912551 1.13200411]
  [1.79156378 1.22793445 1.18187254 1.34125704 1.31904492]
  [1.25473676 1.03580231 1.71275198 1.75110648 1.50934417]]

 [[1.40435043 1.38011305 1.73202142 1.66732849 1.76356686]
  [1.98673213 1.62082971 1.54097282 1.99770969 1.81250361]
  [1.09332444 1.25724727 1.50133725 1.1262348  1.77804693]]]


In [14]:

#12. Multiply a and c. Assign the result to e.

e=a*c

e

array([[[0.80616579, 0.87630752, 0.46481359, 0.67912551, 0.13200411],
        [0.79156378, 0.22793445, 0.18187254, 0.34125704, 0.31904492],
        [0.25473676, 0.03580231, 0.71275198, 0.75110648, 0.50934417]],

       [[0.40435043, 0.38011305, 0.73202142, 0.66732849, 0.76356686],
        [0.98673213, 0.62082971, 0.54097282, 0.99770969, 0.81250361],
        [0.09332444, 0.25724727, 0.50133725, 0.1262348 , 0.77804693]]])

In [15]:

#13. Does e equal to a? Why or why not?

#Estamos multiplicando por 1,por lo que nos dara igual

In [16]:

#14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"

d_max=d.max()
d_min= d.min()
d_mean= d.mean()

print(d_min)
print(d_min)
print(d_mean)

1.035802311700294
1.035802311700294
1.5248716619595841


In [17]:

#15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.

f=np.empty((2,3,5))
f.shape

(2, 3, 5)

In [19]:

"""
#16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.
"""

# valores entre dmi y dmean, intro 25

#valores entre dmean y dmax, intro 75

#valores iguales a dmen, intro 50

#valores igual a dmin, intro 0

#valores iguales a dmax, intro 100

for x in range(d.shape[0]):
    for y in range(d.shape[1]):
        for z in range(d.shape[2]):
            if d[x,y,z] > d_min and d[x,y,z] < d_mean:
                f[x,y,z] = 25
            elif d[x,y,z] > d_mean and d[x,y,z] < d_max:
                f[x,y,z] = 75
            elif d[x,y,z] == d_mean:
                f[x,y,z] = 50
            elif d[x,y,z] == d_min:
                f[x,y,z] = 0
            elif d[x,y,z] == d_max:
                f[x,y,z] = 100


In [20]:

"""
#17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])
"""
print(d)
print(f)


[[[1.80616579 1.87630752 1.46481359 1.67912551 1.13200411]
  [1.79156378 1.22793445 1.18187254 1.34125704 1.31904492]
  [1.25473676 1.03580231 1.71275198 1.75110648 1.50934417]]

 [[1.40435043 1.38011305 1.73202142 1.66732849 1.76356686]
  [1.98673213 1.62082971 1.54097282 1.99770969 1.81250361]
  [1.09332444 1.25724727 1.50133725 1.1262348  1.77804693]]]
[[[ 75.  75.  25.  75.  25.]
  [ 75.  25.  25.  25.  25.]
  [ 25.   0.  75.  75.  25.]]

 [[ 25.  25.  75.  75.  75.]
  [ 75.  75.  75. 100.  75.]
  [ 25.  25.  25.  25.  75.]]]


In [ ]:

"""
#18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.
"""