# 1. Import the NUMPY package under the name np.

In [3]:
import numpy as np

# 2. Print the NUMPY version and the configuration.

In [4]:
print('Numpy version:', np.__version__)

Numpy version: 1.24.3


# 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
# Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [5]:
a = np.random.random((2, 3, 5)) 

In [6]:
a= np.empty ((2,3,5))
for i in range (2):
    for x in range(3):
        for y in range(5):
            a[i, x, y] = np.random.rand()

In [7]:
a= np.random.random (2*3*5).reshape(2,3,5)

# 4. Print a.

In [8]:
print (a)

[[[0.92834097 0.28293673 0.85169365 0.4175109  0.88626683]
  [0.53762954 0.3776229  0.74432864 0.01608092 0.55251652]
  [0.08118653 0.90060949 0.28627268 0.87561976 0.51346514]]

 [[0.82065775 0.55581512 0.71792449 0.0900168  0.41706534]
  [0.61250775 0.95921788 0.01663627 0.55506213 0.03677809]
  [0.5493316  0.30988592 0.60296111 0.57649675 0.93647513]]]


# 5. Create a 5x2x3 3-dimensional array with all values equaling 1.
#Assign the array to variable "b"

In [9]:
b = np.ones((5,2,3)) 


# 6. Print b.

In [10]:
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


# 7. Do a and b have the same size? How do you prove that in Python code?

In [11]:
a.size == b.size

True

# 8. Are you able to add a and b? Why or why not?

It is not possible because of the shape. If we transpose it, then yes. 

# 9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".

In [12]:
c= b.transpose((1,2,0))
c

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

# 10. Try to add a and c. Now it should work. Assign the sum to varialbe "d". But why does it work now?

In [13]:
d= a+c
d

array([[[1.92834097, 1.28293673, 1.85169365, 1.4175109 , 1.88626683],
        [1.53762954, 1.3776229 , 1.74432864, 1.01608092, 1.55251652],
        [1.08118653, 1.90060949, 1.28627268, 1.87561976, 1.51346514]],

       [[1.82065775, 1.55581512, 1.71792449, 1.0900168 , 1.41706534],
        [1.61250775, 1.95921788, 1.01663627, 1.55506213, 1.03677809],
        [1.5493316 , 1.30988592, 1.60296111, 1.57649675, 1.93647513]]])

# 11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.

In [14]:
a

array([[[0.92834097, 0.28293673, 0.85169365, 0.4175109 , 0.88626683],
        [0.53762954, 0.3776229 , 0.74432864, 0.01608092, 0.55251652],
        [0.08118653, 0.90060949, 0.28627268, 0.87561976, 0.51346514]],

       [[0.82065775, 0.55581512, 0.71792449, 0.0900168 , 0.41706534],
        [0.61250775, 0.95921788, 0.01663627, 0.55506213, 0.03677809],
        [0.5493316 , 0.30988592, 0.60296111, 0.57649675, 0.93647513]]])

In [15]:
d

array([[[1.92834097, 1.28293673, 1.85169365, 1.4175109 , 1.88626683],
        [1.53762954, 1.3776229 , 1.74432864, 1.01608092, 1.55251652],
        [1.08118653, 1.90060949, 1.28627268, 1.87561976, 1.51346514]],

       [[1.82065775, 1.55581512, 1.71792449, 1.0900168 , 1.41706534],
        [1.61250775, 1.95921788, 1.01663627, 1.55506213, 1.03677809],
        [1.5493316 , 1.30988592, 1.60296111, 1.57649675, 1.93647513]]])

Podemos ver como en la matriz d se suma el valor 1 a la matriz a.

# 12. Multiply a and c. Assign the result to e.

In [16]:
e= a*c
e

array([[[0.92834097, 0.28293673, 0.85169365, 0.4175109 , 0.88626683],
        [0.53762954, 0.3776229 , 0.74432864, 0.01608092, 0.55251652],
        [0.08118653, 0.90060949, 0.28627268, 0.87561976, 0.51346514]],

       [[0.82065775, 0.55581512, 0.71792449, 0.0900168 , 0.41706534],
        [0.61250775, 0.95921788, 0.01663627, 0.55506213, 0.03677809],
        [0.5493316 , 0.30988592, 0.60296111, 0.57649675, 0.93647513]]])

# 13. Does e equal to a? Why or why not?

In [17]:
e==a

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

Si, ya que lo hemos multiplicado por el mismo determinante que es 1 de la matriz. 

# 14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"


In [18]:
d_max=d.max()
d_max

1.9592178794014825

In [19]:
d_min=d.min()
d_min

1.0160809246100606

In [20]:
d_mean=d.mean()
d_mean

1.5336304450681897

# 15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.


In [22]:
t=(2,3,5)
f=np.empty(t)
print(f)


[[[0.92834097 0.28293673 0.85169365 0.4175109  0.88626683]
  [0.53762954 0.3776229  0.74432864 0.01608092 0.55251652]
  [0.08118653 0.90060949 0.28627268 0.87561976 0.51346514]]

 [[0.82065775 0.55581512 0.71792449 0.0900168  0.41706534]
  [0.61250775 0.95921788 0.01663627 0.55506213 0.03677809]
  [0.5493316  0.30988592 0.60296111 0.57649675 0.93647513]]]


# 16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.

In [32]:
f = np.zeros_like(d)

for i in range(d.shape[0]):
    for j in range(d.shape[1]):
        for k in range(d.shape[2]):
            if d_min < d[i, j, k] < d_mean:
                f[i, j, k] = 25
            elif d_mean < d[i, j, k] < d_max:
                f[i, j, k] = 75
            elif d[i, j, k] == d_mean:
                f[i, j, k] = 50
            elif d[i, j, k] == d_min:
                f[i, j, k] = 0
            elif d[i, j, k] == d_max:
                f[i, j, k] = 100
f  

array([[[ 75.,  25.,  75.,  25.,  75.],
        [ 75.,  25.,  75.,   0.,  75.],
        [ 25.,  75.,  25.,  75.,  25.]],

       [[ 75.,  75.,  75.,  25.,  25.],
        [ 75., 100.,  25.,  75.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]]])

# 17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])
"""

In [29]:
d

array([[[1.92834097, 1.28293673, 1.85169365, 1.4175109 , 1.88626683],
        [1.53762954, 1.3776229 , 1.74432864, 1.01608092, 1.55251652],
        [1.08118653, 1.90060949, 1.28627268, 1.87561976, 1.51346514]],

       [[1.82065775, 1.55581512, 1.71792449, 1.0900168 , 1.41706534],
        [1.61250775, 1.95921788, 1.01663627, 1.55506213, 1.03677809],
        [1.5493316 , 1.30988592, 1.60296111, 1.57649675, 1.93647513]]])

In [30]:
f

array([[[ 75.,  25.,  75.,  25.,  75.],
        [ 75.,  25.,  75.,   0.,  75.],
        [ 25.,  75.,  25.,  75.,  25.]],

       [[ 75.,  75.,  75.,  25.,  25.],
        [ 75., 100.,  25.,  75.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]]])