In [1]:
#1. Import the NUMPY package under the name np.
import numpy as np

In [2]:
#2. Print the NUMPY version and the configuration.
print('Numpy Version:', np.__version__)

Numpy Version: 1.24.3


In [3]:
#3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
# Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?
a=np.random.random((2,3,5))

a

array([[[0.54212466, 0.10400055, 0.26510728, 0.32735691, 0.09906163],
        [0.89939273, 0.2644968 , 0.30132805, 0.01749753, 0.6296834 ],
        [0.0743534 , 0.69186829, 0.52782456, 0.20799629, 0.32073104]],

       [[0.017374  , 0.37876092, 0.41636817, 0.55108403, 0.43043815],
        [0.83463237, 0.5194411 , 0.90541559, 0.24565794, 0.98742564],
        [0.57432836, 0.30977051, 0.31346565, 0.20307445, 0.19316639]]])

In [4]:
shape = (2, 3, 5)
a = np.empty(shape)

for i in range(shape[0]):
    for j in range(shape[1]):
        for k in range(shape[2]):
            a[i, j, k] = np.random.random()

a

array([[[0.6671661 , 0.30272348, 0.78491439, 0.63846204, 0.44761597],
        [0.55273483, 0.63075345, 0.2767653 , 0.09104706, 0.24140134],
        [0.70204151, 0.79283785, 0.65104864, 0.21503311, 0.76447068]],

       [[0.32773849, 0.48471275, 0.65257186, 0.64936964, 0.75342442],
        [0.42790583, 0.2388563 , 0.39432007, 0.01243007, 0.10492819],
        [0.87328791, 0.73174253, 0.66931533, 0.76701811, 0.69213591]]])

In [5]:
#4. Print a.
print(a)

[[[0.6671661  0.30272348 0.78491439 0.63846204 0.44761597]
  [0.55273483 0.63075345 0.2767653  0.09104706 0.24140134]
  [0.70204151 0.79283785 0.65104864 0.21503311 0.76447068]]

 [[0.32773849 0.48471275 0.65257186 0.64936964 0.75342442]
  [0.42790583 0.2388563  0.39432007 0.01243007 0.10492819]
  [0.87328791 0.73174253 0.66931533 0.76701811 0.69213591]]]


In [6]:
#5. Create a 5x2x3 3-dimensional array with all values equaling 1.
#Assign the array to variable "b"
b=np.ones((5,2,3))

b

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [7]:
#6. Print b.
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


In [8]:
#7. Do a and b have the same size? How do you prove that in Python code?
#Sí
a.size==b.size

True

In [9]:
#8. Are you able to add a and b? Why or why not?
#no, porque no tienen la misma forma.
a.shape==b.shape

False

In [10]:
#9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".
c=b.transpose((1,2,0))

c

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [11]:
#10. Try to add a and c. Now it should work. Assign the sum to varialbe "d". But why does it work now?
d=a+c

d

array([[[1.6671661 , 1.30272348, 1.78491439, 1.63846204, 1.44761597],
        [1.55273483, 1.63075345, 1.2767653 , 1.09104706, 1.24140134],
        [1.70204151, 1.79283785, 1.65104864, 1.21503311, 1.76447068]],

       [[1.32773849, 1.48471275, 1.65257186, 1.64936964, 1.75342442],
        [1.42790583, 1.2388563 , 1.39432007, 1.01243007, 1.10492819],
        [1.87328791, 1.73174253, 1.66931533, 1.76701811, 1.69213591]]])

In [12]:
#11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.
print(a)
print(d)
#la diferencia es que a la amtriz d se le ha sumado 1 a cada elemento de la matriz

[[[0.6671661  0.30272348 0.78491439 0.63846204 0.44761597]
  [0.55273483 0.63075345 0.2767653  0.09104706 0.24140134]
  [0.70204151 0.79283785 0.65104864 0.21503311 0.76447068]]

 [[0.32773849 0.48471275 0.65257186 0.64936964 0.75342442]
  [0.42790583 0.2388563  0.39432007 0.01243007 0.10492819]
  [0.87328791 0.73174253 0.66931533 0.76701811 0.69213591]]]
[[[1.6671661  1.30272348 1.78491439 1.63846204 1.44761597]
  [1.55273483 1.63075345 1.2767653  1.09104706 1.24140134]
  [1.70204151 1.79283785 1.65104864 1.21503311 1.76447068]]

 [[1.32773849 1.48471275 1.65257186 1.64936964 1.75342442]
  [1.42790583 1.2388563  1.39432007 1.01243007 1.10492819]
  [1.87328791 1.73174253 1.66931533 1.76701811 1.69213591]]]


In [13]:
#12. Multiply a and c. Assign the result to e.
e=a*c

e

array([[[0.6671661 , 0.30272348, 0.78491439, 0.63846204, 0.44761597],
        [0.55273483, 0.63075345, 0.2767653 , 0.09104706, 0.24140134],
        [0.70204151, 0.79283785, 0.65104864, 0.21503311, 0.76447068]],

       [[0.32773849, 0.48471275, 0.65257186, 0.64936964, 0.75342442],
        [0.42790583, 0.2388563 , 0.39432007, 0.01243007, 0.10492819],
        [0.87328791, 0.73174253, 0.66931533, 0.76701811, 0.69213591]]])

In [14]:
#13. Does e equal to a? Why or why not?
e==a
#Sí, porque al haber multiplicado todos los elementos por el mismo valor el determinante de la matriz sigue siendo el mismo.

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

In [15]:
#14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"
d_max=d.max()
print(d_max)

1.8732879065092893


In [16]:
d_min=d.min()
print(d_min)

1.012430065391972


In [17]:
d_mean=d.mean()
print(d_mean)

1.5179591057193307


In [18]:
#15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.
t=(2,3,5)
f=np.empty(t)
print(f)

[[[0.6671661  0.30272348 0.78491439 0.63846204 0.44761597]
  [0.55273483 0.63075345 0.2767653  0.09104706 0.24140134]
  [0.70204151 0.79283785 0.65104864 0.21503311 0.76447068]]

 [[0.32773849 0.48471275 0.65257186 0.64936964 0.75342442]
  [0.42790583 0.2388563  0.39432007 0.01243007 0.10492819]
  [0.87328791 0.73174253 0.66931533 0.76701811 0.69213591]]]


In [19]:
#16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
#If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
#If a value equals to d_mean, assign 50 to the corresponding value in f.
#Assign 0 to the corresponding value(s) in f for d_min in d.
#Assign 100 to the corresponding value(s) in f for d_max in d.
#In the end, f should have only the following values: 0, 25, 50, 75, and 100.
#Note: you don't have to use Numpy in this question.

In [20]:
f = np.zeros_like(d)
for i in range(d.shape[0]):
    for j in range(d.shape[1]):
        for k in range(d.shape[2]):
            if d_min < d[i, j, k] < d_mean:
                f[i, j, k] = 25
            elif d_mean < d[i, j, k] < d_max:
                f[i, j, k] = 75
            elif d[i, j, k] == d_mean:
                f[i, j, k] = 50
            elif d[i, j, k] == d_min:
                f[i, j, k] = 0
            elif d[i, j, k] == d_max:
                f[i, j, k] = 100
f

array([[[ 75.,  25.,  75.,  75.,  25.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  75.,  75.,  25.,  75.]],

       [[ 25.,  25.,  75.,  75.,  75.],
        [ 25.,  25.,  25.,   0.,  25.],
        [100.,  75.,  75.,  75.,  75.]]])

In [24]:
#17. Print d and f. Do you have your expected f?
#For instance, if your d is:
#array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
#        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
#        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
#
#       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
#        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
#        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])
#
#Your f should be:
#array([[[ 75.,  75.,  75.,  25.,  75.],
#        [ 75.,  75.,  25.,  25.,  25.],
#        [ 75.,  25.,  75.,  75.,  75.]],
#
#       [[ 25.,  25.,  25.,  25., 100.],
#        [ 75.,  75.,  75.,  75.,  75.],
#        [ 25.,  75.,   0.,  75.,  75.]]])


In [25]:
print(f)
print(d)

[[[ 75.  25.  75.  75.  25.]
  [ 75.  75.  25.  25.  25.]
  [ 75.  75.  75.  25.  75.]]

 [[ 25.  25.  75.  75.  75.]
  [ 25.  25.  25.   0.  25.]
  [100.  75.  75.  75.  75.]]]
[[[1.6671661  1.30272348 1.78491439 1.63846204 1.44761597]
  [1.55273483 1.63075345 1.2767653  1.09104706 1.24140134]
  [1.70204151 1.79283785 1.65104864 1.21503311 1.76447068]]

 [[1.32773849 1.48471275 1.65257186 1.64936964 1.75342442]
  [1.42790583 1.2388563  1.39432007 1.01243007 1.10492819]
  [1.87328791 1.73174253 1.66931533 1.76701811 1.69213591]]]
